before_script:
  - apt-get update -qq && apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - nvm install v5.10.1
stages:
  - test

job1:
  - stage: test
  - script:
     - node test.js
  - only:
     - master
  - tags:
     - docker