image: docker-node
before_script:
  - npm install
stages:
  - build
  - test
  - deploy
test:
  stage: test
  script:
    - mocha
  tags:
    - docker
deploy:
  stage: deploy
  script:
    - npm publish