image: docker-node
service: mysql
before_script:
  - npm install
stages:
  - build
  - test
  - deploy
test:
  stage: test
  script:
    - mocha
  tags:
    - docker
deploy:
  stage: deploy
  only:
    - master
    - dev
  script:
    - npm publish