image: node:5.10.1
before_script:
  - apt-get update -yqq && apt-get install -y mocha
  - npm install
  - npm install -g mocha
stages:
  - build
  - test
job1:
  stage: test
  script:
    - mocha
  tags:
    - docker